defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 0
float32_matmul_precision: high

# model loading
diet_name: Comb
scheme_id: CombDiet
backbone: resnet50
stage_epochs: [10, 6, 1, 5, 1, 2, 3, 2, 70]
reload_freq: 1
num_classes: 10
num_classes_linear: 10
batch_size_per_device: 64


# dataset
map_path: say_in1k_map.json
cue_conflict_root: texture-vs-shape-master/stimuli/style-transfer-preprocessed-512

# -------- models --------
models:
 - method: simclr
   ckpt_path: /path/to/SAY/Comb-resnet50-scheme_CombDiet/seed_0/checkpoints/pretrain/last.ckpt
   lin_ckpt_path: /path/to/SAY/Comb-resnet50-scheme_CombDiet/seed_0/checkpoints/linprobe/last.ckpt

 - method: simclr
   ckpt_path: /path/to/SAY/Comb-resnet50-scheme_SHF/seed_0/checkpoints/pretrain/last.ckpt
   lin_ckpt_path: /path/to/SAY/Comb-resnet50-scheme_SHF/seed_0/checkpoints/linprobe/last.ckpt

 - method: simclr
   ckpt_path: /path/to/SAY/Comb-resnet50-scheme_STD/seed_0/checkpoints/pretrain/last.ckpt
   lin_ckpt_path: /path/to/SAY/Comb-resnet50-scheme_STD/seed_0/checkpoints/linprobe/last.ckpt